bacn/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('', include('activitypub.urls')),
    path('accounts/', include('allauth.urls')),
    path('blog/', include('blog.urls')),
]

blog/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import include, path
from .views import BlogView, CreatePostView, TagView

app_name = 'blog'
urlpatterns = [
    path('post/create', login_required(CreatePostView.as_view()), name='create_post'),
    path('<str:username>', login_required(BlogView.as_view()), name='view_blog'),
    path('tags/<str:tag>', TagView.as_view(), name='tag'),
]

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.template import loader
from django.urls import reverse


class Blog(models.Model):
    name = models.TextField(max_length=50, null=False)
    owner = models.ForeignKey(User, null=False, on_delete=models.CASCADE)


class Tag(models.Model):
    text = models.TextField(max_length=120, null=False)

    def get_absolute_url(self):
        return reverse('blog:tag', args=[str(self.text)])

    @classmethod
    def from_tags_str(cls, tags_str):
        """Using a provided string of tags, get the database objects for each of those tags.

        :param tags_str: string of tags from a post form
        :type tags_str: str
        :return: list of Tag items for each tag in the string
        :rtype: list of Tag
        """

        # If tag_str is invalid or empty return None
        if '#' not in tags_str:
            return []

        # Get all unique tags from the provided string
        tag_strs_set = set(tag_str.strip() for tag_str in tags_str.split('#')[1:])

        return list(cls.objects.get_or_create(text=tag_str)[0] for tag_str in tag_strs_set if tag_str)


class Post(models.Model):
    user = models.ForeignKey(User, null=False, on_delete=models.CASCADE)
    blog = models.ForeignKey(Blog, null=True, on_delete=models.CASCADE)
    title = models.CharField(max_length=60)
    text = models.TextField(max_length=500000, null=False)
    tags = models.ManyToManyField(Tag)

    @property
    def as_template(self):
        template = loader.get_template('blog/blog_post.html')
        context = {
            "title": self.title,
            "user": self.user,
            "text": self.text,
            "tags": self.tags.all()
        }
        return template.render(context)

blog/forms.py
from django.forms import ModelForm
from .models import Post


class PostForm(ModelForm):
    class Meta:
        model = Post
        exclude = ('tags',)

    @classmethod
    def from_post_data(cls, post_data, user_id):
        """Create a PostForm from a post request.
        """
        form_data = dict(
            user=user_id
        )

        # using **post_data or form_data.update results in values being list of str rather than str
        for k, v in post_data.items():
            form_data[k] = v

        return cls(form_data)

blog/views.py
import re

from django.contrib.auth.models import User
from django.http import HttpResponseNotFound
from django.shortcuts import render
from django.views.generic.base import TemplateView
from allauth.socialaccount.models import SocialAccount

from core.models import UserProfile
from .forms import PostForm
from .models import Tag


class CreatePostView(TemplateView):

    template_name = "blog/create_post.html"

    def get_context_data(self, *args, form=None, **kwargs):
        context = super().get_context_data(*args, **kwargs)

        context['form'] = form or PostForm()
        return context

    def post(self, request, *args, **kwargs):
        """Handle post requests for the Create Post view.
        """

        # Get or create tag objects for every tag listed in the form
        tags = Tag.from_tags_str(self.request.POST['tags'])

        form = PostForm.from_post_data(
            post_data=self.request.POST,
            user_id=self.request.user.id
        )

        if form.is_valid():
            new_post = form.save()
            new_post.tags.set(tags)

        context = self.get_context_data(form=form)
        context['form_tags'] = ' '.join(['#' + t.text for t in tags])
        return render(request, template_name=self.template_name, context=context)


class BlogView(TemplateView):

    template_name = "blog/blog.html"

    # ProfileView.user is the user that is currently logged in.
    user = None

    # ProfileView.profile is the profile being viewed.  If none is specified it will be the profile
    # of the ProfileView.user
    profile = None

    def dispatch(self, request, *args, **kwargs):
        # Since rest_framework doesn't support jrd+json requests, a workaround is necessary until
        # it does
        if re.match(r'application/(activity\|ld)+json', request.META.get('HTTP_ACCEPT', '')):
            return resolve(reverse('')).func(request, *args, **kwargs)
        return super(BlogView, self).dispatch(request, *args, **kwargs)

    def get(self, *args, **kwargs):
        """Before get_context_data is called, the profile is located. or a 404 is returned."""
        # Get an account if specified, or try to get account that's logged in
        self.user = self.request.user
        try:
            profile_user = User.objects.get(username=kwargs['username'])
        except KeyError:
            profile_user = self.user
        except User.DoesNotExist:
            return HttpResponseNotFound('<h1>Page not found</h1>')

        self.blog_posts = profile_user.post_set.all()[::-1]
        self.profile, created = UserProfile.objects.get_or_create(user=profile_user)

        return super().get(*args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        social_account = SocialAccount.objects.get(user=self.profile.user)

        context['user'] = self.user
        context['profile'] = self.profile
        context['social'] = {
            # Todo: Fix social link
            #'link': social_account.extra_data.get('link'),
            'provider': social_account.provider
        }
        context['blog_posts'] = self.blog_posts
        return context


class TagView(TemplateView):
    pass

blog/templates/blog/forms/text_post.html
  <form method="post" action="{% url 'blog:create_post' %}">
    {% csrf_token %}
    <div class="input-field col s12">
      <input id="title" name="title" type="text" class="validate" value="{% if form.title.value %}{{ form.title.value }}{% endif %}">
      <label for="title">Title</label>
    </div>
    <div class="input-field col s12">
      <textarea id="text" name="text" class="materialize-textarea">{% if form.text.value %}{{ form.text.value }}{% endif %}</textarea>
      <label for="text">Your text</label>
    </div>
    <div class="input-field col s12">
      <input id="tags" name="tags" type="text" class="validate" value="{{ form_tags }}">
      <label for="tags">#Tags</label>
    </div>
    <button class="btn waves-effect waves-light"
            type="submit"
            name="action">
      Post <i class="material-icons right">send</i>
    </button>
  </form>

blog/templates/blog/forms/text_post_modal.html
  <div id="create_post_modal" class="modal">
    <div class="modal-content">
      <form method="post" action="{% url 'blog:create_post' %}">
        {% csrf_token %}
        <h4>
          <div class="input-field col s12">
            <input id="title" name="title" type="text" class="validate" value="{% if form.title.value %}{{ form.title.value }}{% endif %}">
            <label for="title">Title</label>
          </div>
        </h4>
        <div class="input-field col s12">
          <textarea id="text" name="text" class="materialize-textarea">{% if form.text.value %}{{ form.text.value }}{% endif %}</textarea>
          <label for="text">Your text</label>
        </div>
        <div class="input-field col s12">
          <input id="tags" name="tags" type="text" class="validate" value="{{ form_tags }}">
          <label for="tags">#Tags</label>
        </div>
      </div>
      <div class="modal-footer">
        <a href="#!" class="left modal-close waves-effect waves-green btn-flat">Close</a>
        <button class="modal-close waves-effect waves-green btn" type="submit">
          Post <i class="material-icons right">send</i>
        </button>
      </form>
    </div>
  </div>