bacn/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('', include('activitypub.urls')),
    path('accounts/', include('allauth.urls')),
    path('blog/', include('blog.urls')),
]

core/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import include, path
from .views import HomeView, ProfileView, SearchView, SettingsView

urlpatterns = [
    path('accounts/profile/', ProfileView.as_view(), name='profile'),
    path('accounts/settings/', login_required(SettingsView.as_view()), name='account_settings'),
    path('', HomeView.as_view(), name='home'),
    path('search', SearchView.as_view(), name='search')
]

core/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from django.utils.translation import gettext_lazy as _

GENDER = (('man', 'Man'), ('woman', 'Woman'))


class UserProfile(models.Model):
    user = models.OneToOneField(User, null=True, related_name="profile",
                                verbose_name=_('User'), on_delete=models.CASCADE)
    gender = models.CharField(
        max_length=40, blank=True, verbose_name=_('Gender'), choices=GENDER)
    avatar = models.ImageField(
        upload_to='userprofiles2/avatars', blank=True, verbose_name=_('Avatar'))
    email_is_verified = models.BooleanField(
        default=False, verbose_name=_('Email is verified'))

    class Meta:
        verbose_name = _('User profile')
        verbose_name_plural = _('User profiles')

    def __str__(self):
        return "User profile: %s" % self.user.username

    def get_absolute_url(self):
        return reverse('blog:view_blog', args=[str(self.user.username)])

core/forms.py
from django import forms


class SettingsForm(forms.Form):
    email = forms.EmailField()
    password = forms.CharField(widget=forms.PasswordInput)
    new_password = forms.CharField(widget=forms.PasswordInput)
    verify_password = forms.CharField(widget=forms.PasswordInput)

    def __init__(self, *args, user=None, **kwargs):
        super().__init__(*args, **kwargs)
        self.user = user

    def clean_password(self):
        password = self.cleaned_data['password']

        if not self.user.check_password(password):
            raise forms.ValidationError("Invalid password")
        return password

    def clean_verify_password(self):
        new_password = self.cleaned_data['new_password']
        verify_password = self.cleaned_data['verify_password']

        if verify_password and new_password != verify_password:
            raise forms.ValidationError("Passwords don't match")
        return verify_password

    def save(self):
        new_password = self.cleaned_data['new_password']
        if new_password:
            self.user.set_password(new_password)
            self.user.save()

core/views.py
from django.contrib.auth.models import User
from django.shortcuts import render
from django.views.generic.base import TemplateView

from .forms import SettingsForm
from blog.views import BlogView
from blog.models import Post, Tag


class HomeView(TemplateView):

    template_name = "core/home.html"


class ProfileView(BlogView):

    template_name = "core/profile.html"


class SearchView(TemplateView):

    template_name = "core/search.html"

    @staticmethod
    def search(search_text, model, attributes):
        """A rudimentary search that looks for all works provided in all attributes provided of the specified model.
        """
        items = set()
        for word in search_text.split():
            for attribute in attributes:
                items |= set(model.objects.filter(**{attribute + '__contains': word}))
        return items

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        search_text = self.request.GET.get('search')
        context.update({
            'people': self.search(search_text, User, ['username', 'first_name', 'last_name']),
            'posts': self.search(search_text, Post, ['title', 'text']),
            'tags': self.search(search_text, Tag, ['text', ])
        })
        return context


class SettingsView(TemplateView):

    template_name = 'core/user_settings.html'

    def get_context_data(self, form=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = form or SettingsForm(initial={
            'email': self.request.user.email,
        })
        return context

    def post(self, request, *args, **kwargs):
        form = SettingsForm(request.POST, user=request.user)
        if form.is_valid():
            form.save()
        context = self.get_context_data(form=form)
        return render(request, template_name=self.template_name, context=context)

core/templates/core/home.html
{% extends 'base.html' %}

{% block content %}
<div class="col l3">
  Bacn is an open source, decentralized social platform for blogging.  Currently the project is in the planning stage.
</div>
<div id="viewport" class="col l6">
  <p>
    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis fermentum massa dolor, vel rhoncus justo finibus nec. Integer quis metus sem. Ut a cursus nibh, vel luctus metus. Fusce id eros fermentum, congue nibh eu, tincidunt justo. Sed auctor posuere hendrerit. Donec in felis purus. Nullam non auctor ex. Quisque luctus ipsum at orci mattis, nec laoreet nisi porttitor. Sed diam dui, condimentum vitae diam et, varius euismod ex. Aenean sit amet ultrices dolor.
  <p>
  </p>
    Ut interdum eget diam ut consectetur. Maecenas blandit sed est a ornare. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla id metus dapibus, rhoncus augue vitae, volutpat risus. Aenean quis scelerisque nisl, ac rhoncus nisl. Phasellus ac erat ut ipsum maximus porta sit amet ac nulla. Aenean efficitur purus sed enim fringilla blandit. Suspendisse ut sapien elit. Nulla cursus, lorem vel interdum ornare, ex massa porta nulla, pellentesque eleifend neque ligula non augue.
  <p>
  </p>
    Interdum et malesuada fames ac ante ipsum primis in faucibus. Donec ligula ex, feugiat eu maximus at, maximus ac tortor. Suspendisse malesuada dapibus tellus nec tincidunt. Sed placerat sodales erat, at lacinia odio laoreet nec. Integer mi mi, ullamcorper id tincidunt vel, volutpat sed dolor. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Etiam velit mi, ullamcorper a erat in, sollicitudin rhoncus tortor. Nam tempor tincidunt lacinia. Proin at neque ac enim ullamcorper tempor id eget risus. Donec laoreet laoreet enim, nec dignissim neque malesuada sit amet. Curabitur hendrerit magna risus. Ut tortor justo, bibendum vitae dignissim in, rutrum at quam. In erat purus, tempor porta scelerisque nec, egestas quis tellus.
  <p>
  </p>
    Quisque maximus purus eget enim dapibus aliquam. Donec leo augue, euismod elementum egestas vel, vestibulum ut quam. Phasellus ac venenatis metus. Vestibulum auctor suscipit eros, ac lacinia magna euismod non. Aliquam iaculis vestibulum tempus. Ut feugiat aliquam mauris, non semper metus imperdiet ut. Fusce sit amet elit et dui auctor auctor sit amet vitae leo. Etiam vel nisi in lectus hendrerit facilisis nec nec tellus. Nullam eget condimentum nisi.
  <p>
  </p>
    Aenean blandit massa quis odio iaculis, non placerat nunc malesuada. Maecenas id porttitor mi. Aenean venenatis, dui id tincidunt dignissim, urna justo tincidunt mauris, et pretium diam justo sit amet dolor. Vestibulum eu aliquam massa. Proin ullamcorper dictum vestibulum. Suspendisse tempor, eros et vulputate eleifend, purus mauris venenatis magna, id porta eros lacus vulputate enim. Proin convallis mattis aliquet. Aliquam laoreet turpis hendrerit tortor placerat, a fringilla justo cursus. Fusce neque nibh, luctus ut interdum ac, ullamcorper tristique risus. Aliquam suscipit sem nisi, sit amet euismod velit molestie et. Nullam ultrices varius ornare. Phasellus consectetur, nisl vel viverra elementum, sapien dolor pulvinar lorem, id lacinia risus metus eu purus. Fusce ut lacinia massa.
  </p>
</div>
{% endblock content %}

core/templates/core/profile.html
{% extends 'base.html' %}

{% block content %}
<div id="viewport" class="col m7 xl6 offset-m1 offset-xl3">
  <div id="new-entry-form"></div>
  <div>
    Blog contents goes here.
  </div>
</div>
<div id="blog-details" class="col l3">
  <div>
    <span id="blog-title">Just another blog</span>
  </div>
  <div>
    <span id="blog-desc">A blog about nothing</span>
  </div>
  <ul class="collection transparent">
    <li class="collection-item transparent">
      Posts
      <a href="#!" class="secondary-content">9001</a>
    </li>
    <li class="collection-item transparent">
      Followers
      <a href="#!" class="secondary-content">42</a>
    </li>
  </ul>
</div>
{% endblock content %}

core/templates/core/search.html
{% extends 'base.html' %}

{% block content %}
<h3>People</h3>
{% for person in people %}
  <a href="{{ person.get_absolute_url }}">{{ person }}</a><br />
{% endfor %}
<h3>Tags</h3>
{% for tag in tags %}
  <a href="{{ tag.get_absolute_url }}">#{{ tag.text }}</a>
{% endfor %}
<br />
<h3>Posts</h3>
{% for post in posts %}
<a href="{{ post.get_absolute_url }}">{{ post.title }}</a> by <a href="{{ post.user.get_absolute_url }}">{{ post.user }}</a><br />
{% endfor %}
{% endblock content %}

core/templates/core/user_settings.html
{% extends 'base.html' %}

{% block head_content %}
<style>
  .collection {
    border: none;
  }
</style>
{% endblock head_content %}

{% block content %}
<div id="viewport" class="col m7 xl6 offset-m1 offset-xl3">
  <form id="settings-form" action="" method="post">
    {% csrf_token %}
    <ul class="collection">
      <li class="collection-item transparent">
        <div class="row">
          <div class="col m3">
            email:
          </div>
          <div class="input-field col m9">
            {{ form.email }}
            <label for="id_email">Email</label>
          </div>
        </div>
      </li>
      <li class="collection-item transparent">
        <div class="row">
          <div class="col m3">
            Password:
          </div>
          <div class="col m9">
            <div class="input-field">
              {{ form.password }}
              <label for="id_password">Current Password</label>
            </div>
            <div class="input-field">
              {{ form.password }}
              <label for="id_new_password">New Password</label>
            </div>
            <div class="input-field">
              {{ form.password }}
              <label for="id_verify_password">Verify Password</label>
            </div>
          </div>
      </li>
    </ul>
    <button class="btn right" type="submit" name="action">Save
      <i class="material-icons right">send</i>
    </button>
  </form>
</div>
{% endblock content %}